ALTER TABLE v1_members
    ADD COLUMN withdrawn_at DATETIME(6) NULL;

ALTER TABLE v1_members
    MODIFY COLUMN status VARCHAR(20)
        NOT NULL
        DEFAULT 'ACTIVE'
        COMMENT 'ACTIVE, INACTIVE, SUSPENDED, WITHDRAWN';