server:
  forward-headers-strategy: native

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

app:
  oauth2:
    authorization-request-cookie:
      secure: true

    flow:
      login-success-redirect-uri: https://www.optional94.com/oauth/callback
      signup-redirect-uri: https://www.optional94.com/oauth/sign-up
      failure-redirect-uri: https://www.optional94.com/login

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  endpoint:
    health:
      show-details: never

    prometheus:
      access: read-only

  metrics:
    tags:
      application: concert-backend

    distribution:
      percentiles-histogram:
        http.server.requests: true

      percentiles:
        http.server.requests:
          - 0.5
          - 0.95
          - 0.99

logging:
  file:
    name: logs/concert-backend.log

  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 14
      total-size-cap: 2GB
      